/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Think' at '17-5-7 上午8:21' with Gradle 2.11
 *
 * @author Think, @date 17-5-7 上午8:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
